### ISSUE TITLE
Create tests

### ISSUE THREAD

**Issue by froi** [fullstacknights/website#14]
I think we should have some sort of tests. 

En el pasado hemos tenido momentos que rompemos algo y tenemos que hacer un scramble para arreglarlo.

What say all of you?

**Comment by eluciano11** [comment]
No lo había pensado pero creo que podemos añadirlos. Tendría que ver cómo hacerlos con Gatsby. Supongo que react-testing-library y jest deben funcionar sin problemas con Gatsby.

**Comment by froi** [comment]
Cool. Creo que para lo que quiero hacer, full automation, los vamos a necesitar.

**Comment by eluciano11** [comment]
Creo que podemos usar Cypress y hacer some validation para cada pagina. 
https://www.cypress.io/blog/2019/09/13/gatsby-webcast-recording/

Voy a look into it.

**Comment by eluciano11** [comment]
As discussed on Slack. Most of the issues that we've had in the past have been visual issues. Using Cypress would be an overkill because will not test any functionality. A better tool for our use case is Percy. Percy is a visual review tool that compares snapshots taken from master vs snapshots from a branch that's on PR.

Examples:
![percy](https://user-images.githubusercontent.com/6109151/70293651-4a3a2500-17b7-11ea-8d40-0aadbced7182.gif)

![percy-2](https://user-images.githubusercontent.com/6109151/70293707-83729500-17b7-11ea-9513-a4abffc3b31a.gif)
